### PR TITLE
SEO-185532 JavaScript PDF Viewer Missing H1

### PR DESCRIPTION
**Pull request by Yvone-Atieno**
Hi @Aishwarya-Ganesan,
|Title|Description|
|--|--|
|Task Category| Missing H1|
|Content Task Link/Mail Screenshot| NA|
|UX task| NA|
|UG PR link| UG -https://github.com/syncfusion-content/javascript-docs/pull/492|
|Ticket/Task link| https://dev.azure.com/Syncfusion-Infrastructure/Syncfusion%20SEO/_workitems/edit/185532/|
|Excel/SharePoint link| https://syncfusion.sharepoint.com/:x:/r/sites/SEOWebsiteAuditing/_layouts/15/Doc.aspx?sourcedoc=%7B1B4A962C-249C-46B6-88CD-E152228D7339%7D&file=Yvone.xlsx&action=default&mobileredirect=true&wdsle=0|

### CODE REVIEW

**Comment by Thahira-Banu** [comment]
Hi @Aishwarya-Ganesan ,
I have reviewed this PR and the changes are fine.

**Comment by Thahira-Banu** [comment]
Hi @Aishwarya-Ganesan ,
I have reviewed this PR and the changes are fine.

**Comment by Thahira-Banu** [comment]
Hi @Aishwarya-Ganesan ,
I have reviewed this PR and the changes are fine.

**Comment by Thahira-Banu** [comment]
Hi @Aishwarya-Ganesan ,
I have reviewed this PR and the changes are fine.

**Comment by Thahira-Banu** [comment]
Hi @Aishwarya-Ganesan ,
I have reviewed this PR and the changes are fine.

**Review by Aishwarya-Ganesan — APPROVED** [review]
fine.

**Pull request merged**
